twig:
    default_path: '%kernel.project_dir%/templates'

    globals:
        site_name: 'Centre Social et Culturel'
        site_name_full: 'Centre Social et Culturel Suzanne Coulomb'
        site_url: 'centresocialcosne.org'
        site_url_full: 'https://www.centresocialcosne.org'
        site_mail: 'info@centresocialcosne.org'
        site_author: 'citizenz7'
        site_description: 'Le Centre Social et Culturel Suzanne Coulomb de Cosne-Cours-sur-Loire (58200), fort d’un enracinement local de 45 ans, développe et renouvelle sans cesse ses activités et projet s’adressant au plus grand nombre. C’est par ses activités et projets qu’il favorise le lien social, socle indispensable à une vie locale riche et épanouissante. Le Centre Social et Culturel Suzanne Coulomb fonde son action sur l’engagement citoyen et véhicule des valeurs où prime l’intérêt collectif.'
        site_location: 'Cosne-Cours-sur-Loire'
        site_address_full: '15, rue de Berry 58200 Cosne-Cours-sur-Loire'
        site_address_tel: '03.86.28.20.96'
        site_version: '1.0.1'