twig:
    default_path: '%kernel.project_dir%/templates'

    globals:
        site_name: 'Centre Social et Culturel'
        site_name_full: 'Centre Social et Culturel Suzanne Coulomb'
        site_url: 'centresocialcosne.org'
        site_url_full: 'https://www.centresocialcosne.org'
        site_mail: 'info@centresocialcosne.org'
        site_author: 'citizenz7'
        site_location: 'Cosne-Cours-sur-Loire'
        site_version: '1.0.1'